### ISSUE TITLE
No need to copy Volo.Abp.AspNetCore.Components.WebAssembly.Theming

### ISSUE THREAD

**Issue by hikalkan** [bartvanhoey/AbpBlazorMyTheme#1]
I think you don't need to copy Volo.Abp.AspNetCore.Components.WebAssembly.Theming. You can continue to use it as NuGet package.

**Comment by bartvanhoey** [comment]
Good Point. I rewrote the article ... much simpler by now ;-)

**Comment by hikalkan** [comment]
We had a bug on the platform (something related parsing your article) and could not publish it.
Unfortunately, someone else already published a similar article: https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b
If you still want, we can publish this too after fixing the bug. Alternatively, you can write a comment under the article https://community.abp.io/articles/creating-a-new-ui-theme-by-copying-the-basic-theme-for-blazor-ui-qaf5ho1b to point here as an alternative implementation. What do you prefer?

**Comment by bartvanhoey** [comment]
I can live with it and it would be stupid to have 2 article about the same😊.  Leave the article from the other author,  he deserves the credits (as I based my article upon his original)

**Comment by hikalkan** [comment]
Thanks for your understanding :)
